### ISSUE TITLE
download template: Error sending file

### ISSUE THREAD

**Issue by anusharanganathan** [anusharanganathan/dataPaperCompanion#50]
I tested with these two docx file added to two journals
[F1000ResearchTemplate.docx](https://github.com/anusharanganathan/data2paper/files/1779314/F1000ResearchTemplate.docx)
[gdata_data_in_brief_template2.docx](https://github.com/anusharanganathan/data2paper/files/1779315/gdata_data_in_brief_template2.docx)

Both of these errors could be due to webrick not being multi threaded

## Using the show method
```
Started GET "/concern/data_papers/j098zb10q/template" for 80.192.245.110 at 2018-03-05 02:42:53 +0000
Cannot render console from 80.192.245.110! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Hyrax::DataPaperTemplateController#show as HTML
  Parameters: {"id"=>"j098zb10q"}
Attempted to init base path `dev`, but it already exists
  Load LDP (7.8ms) http://localhost:8984/rest/dev/j0/98/zb/10/j098zb10q Service: 58635440
  Load LDP (7.8ms) http://localhost:8984/rest/dev/5t/34/sj/56/5t34sj56t Service: 58635440
  Load LDP (4.6ms) http://localhost:8984/rest/dev/k3/56/94/32/k3569432s Service: 58635440
  Load LDP (4.6ms) http://localhost:8984/rest/dev/9g/54/xh/64/9g54xh64n Service: 58635440
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Role Load (0.4ms)  SELECT "roles".* FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1  [["user_id", 2]]
Usergroups are ["public", "admin", "registered"]
  Role Exists (0.4ms)  SELECT  1 AS one FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1 AND "roles"."name" = $2 LIMIT $3  [["user_id", 2], ["name", "admin"], ["LIMIT", 1]]
  Hyrax::Feature Load (0.3ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "transfer_works"], ["LIMIT", 1]]
  Hyrax::Feature Load (0.3ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "proxy_deposit"], ["LIMIT", 1]]
  Load LDP (6.6ms) http://localhost:8984/rest/dev/k3/56/94/32/k3569432s/files/15ae8649-e08e-4214-a034-83f3d796e177/fcr:metadata Service: 58635440
  Load LDP (6.3ms) http://localhost:8984/rest/dev/k3/56/94/32/k3569432s/files/15ae8649-e08e-4214-a034-83f3d796e177 Service: 58635440
  Rendering text template
  Rendered text template (0.0ms)
Sent data paper_template_j098zb10q_gdata_data_in_brief_template2.docx (1.6ms)
Completed 200 OK in 307ms (Views: 1.4ms | ActiveRecord: 1.9ms)

[2018-03-05 02:42:53] ERROR NoMethodError: undefined method `split' for 11566:Integer
        /home/data2paper/.rvm/gems/ruby-2.4.2/gems/rack-2.0.3/lib/rack/handler/webrick.rb:98:in `block in service'
        /home/data2paper/.rvm/gems/ruby-2.4.2/gems/rack-2.0.3/lib/rack/utils.rb:454:in `block in each'
        /home/data2paper/.rvm/gems/ruby-2.4.2/gems/rack-2.0.3/lib/rack/utils.rb:453:in `each'
        /home/data2paper/.rvm/gems/ruby-2.4.2/gems/rack-2.0.3/lib/rack/utils.rb:453:in `each'
        /home/data2paper/.rvm/gems/ruby-2.4.2/gems/rack-2.0.3/lib/rack/handler/webrick.rb:90:in `service'
        /home/data2paper/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
        /home/data2paper/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
        /home/data2paper/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
127.0.0.1 - - [05/Mar/2018:02:42:53 UTC] "GET /concern/data_papers/j098zb10q/template HTTP/1.0" 500 330
- -> /concern/data_papers/j098zb10q/template
```
## Using the generate method

```
Started PATCH "/concern/data_papers/j098zb10q/template" for 80.192.245.110 at 2018-03-05 02:34:04 +0000
Cannot render console from 80.192.245.110! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
   (0.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
ActiveFedora: loading fedora config from /home/data2paper/data2paper/config/fedora.yml
ActiveFedora: loading solr config from /home/data2paper/data2paper/config/solr.yml
Processing by Hyrax::DataPaperTemplateController#generate as JSON
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"2mhGAEDBUSMmr/SsvzAIn6jUZmOFIfOAkqgUO7UCLtfi4c1hQA2TA/P47E/r1Ic6s/hSr0ni/pUhIl5Poq1Tgw==", "data_paper"=>{"title"=>["Test 3", 
""], "creator_nested_attributes"=>{"0"=>{"name"=>["Anusha Ranganathan"], "affiliation"=>[""], "role"=>["Author"], "_destroy"=>"false", "id"=>"http://localhost:8984/rest/dev/j0/9
8/zb/10/j098zb10q#persong69907919949240"}, "1"=>{"name"=>[""], "affiliation"=>[""], "role"=>[""], "_destroy"=>"false"}}, "description"=>[""], "keyword"=>[""], "subject"=>[""], "
date_attributes"=>{"0"=>{"description"=>[""], "date"=>[""], "_destroy"=>"false"}}, "relation_attributes"=>{"0"=>{"label"=>[""], "url"=>[""], "relationship_name"=>[""], "_destroy
"=>"false"}}, "tagged_version"=>"", "source"=>[""], "note"=>"", "status"=>"draft", "representative_id"=>"sn009x76k", "thumbnail_id"=>"sn009x76k", "journal_id"=>"mg74qm08d", "lic
ense_nested_attributes"=>{"0"=>{"webpage"=>[""], "_destroy"=>"false", "id"=>"http://localhost:8984/rest/dev/j0/98/zb/10/j098zb10q#rightsg58061620"}, "1"=>{"webpage"=>[""], "_des
troy"=>"false"}}, "rights_statement"=>"Need to add the declaration statement", "permissions_attributes"=>{"1"=>{"access"=>"edit", "id"=>"43e235c0-8876-421d-8b79-cfe867aab1e0/6b/
6d/cf/25/6b6dcf25-ce80-49e9-9085-c90ffd5f74a6"}}, "version"=>"W/\"4e55306b5768afe816eea2c01ee79dedd4552848\"", "statement_agreed"=>"0"}, "file_set"=>{"resource_type"=>["data pap
er", "supplementary file", "data paper"]}, "#"=>"", "new_user_name_skel"=>"", "new_user_permission_skel"=>"none", "new_group_name_skel"=>"Select a group", "new_group_permission_
skel"=>"none", "id"=>"j098zb10q"}
Attempted to init base path `dev`, but it already exists
  Load LDP (8.4ms) http://localhost:8984/rest/dev/j0/98/zb/10/j098zb10q Service: 70297811697440
  Load LDP (8.8ms) http://localhost:8984/rest/dev/5t/34/sj/56/5t34sj56t Service: 70297811697440
  Load LDP (4.8ms) http://localhost:8984/rest/dev/k3/56/94/32/k3569432s Service: 70297811697440
  Load LDP (4.4ms) http://localhost:8984/rest/dev/9g/54/xh/64/9g54xh64n Service: 70297811697440
  User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Role Load (0.7ms)  SELECT "roles".* FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1  [["user_id", 2]]
Usergroups are ["public", "admin", "registered"]
  Role Exists (1.2ms)  SELECT  1 AS one FROM "roles" INNER JOIN "roles_users" ON "roles"."id" = "roles_users"."role_id" WHERE "roles_users"."user_id" = $1 AND "roles"."name" = $
2 LIMIT $3  [["user_id", 2], ["name", "admin"], ["LIMIT", 1]]
  Hyrax::Feature Load (0.5ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "transfer
_works"], ["LIMIT", 1]]
  Hyrax::Feature Load (0.3ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "proxy_de
posit"], ["LIMIT", 1]]
Unpermitted parameters: :date_attributes, :relation_attributes, :tagged_version, :source, :note, :status, :representative_id, :thumbnail_id, :license_nested_attributes, :rights_
statement, :permissions_attributes, :version, :statement_agreed
  Load LDP (5.8ms) http://localhost:8984/rest/dev/ne/w2/ne/w3/new2new3new Service: 70297811697440
  Load LDP (3.4ms) http://localhost:8984/rest/dev/e9/d5/81/ef/e9d581ef-78cd-4353-8a31-878b4cdb7b68 Service: 70297811697440
  Load LDP (7.3ms) http://localhost:8984/rest/dev/mg/74/qm/08/mg74qm08d Service: 70297811697440
  Load LDP (10.9ms) http://localhost:8984/rest/dev/ne/w2/ne/w3/new2new3new Service: 70297811697440
Started GET "/notifications/endpoint" for 80.192.245.110 at 2018-03-05 02:34:06 +0000
Cannot render console from 80.192.245.110! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Started GET "/notifications/endpoint/"[non-WebSocket] for 80.192.245.110 at 2018-03-05 02:34:06 +0000
Failed to upgrade to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: close, HTTP_UPGRADE: )
Finished "/notifications/endpoint/"[non-WebSocket] for 80.192.245.110 at 2018-03-05 02:34:06 +0000
  Sipity::Entity Load (0.4ms)  SELECT  "sipity_entities".* FROM "sipity_entities" WHERE "sipity_entities"."proxy_for_global_id" = $1 LIMIT $2  [["proxy_for_global_id", "gid://da
ta2paper/DataPaper/new2new3new"], ["LIMIT", 1]]

127.0.0.1 - - [05/Mar/2018:02:34:06 UTC] "GET /notifications/endpoint HTTP/1.0" 404 14
- -> /notifications/endpoint
  Load LDP (4.4ms) http://localhost:8984/rest/dev/e9/d5/81/ef/e9d581ef-78cd-4353-8a31-878b4cdb7b68 Service: 70297811697440
  Load LDP (2.3ms) http://localhost:8984/rest/dev/ne/w2/ne/w3/new2new3new/list_source Service: 70297811697440
  Load LDP (1.9ms) http://localhost:8984/rest/dev/ne/w2/ne/w3/new2new3new/list_source Service: 70297811697440
  Load LDP (4.6ms) http://localhost:8984/rest/dev/h7/02/q6/36/h702q636h Service: 70297811697440
  Load LDP (9.7ms) http://localhost:8984/rest/dev/sq/87/bt/60/sq87bt605 Service: 70297811697440
  Load LDP (5.1ms) http://localhost:8984/rest/dev/h7/02/q6/36/h702q636h/files/20579b2a-75ab-4fab-80cb-3bdaf6ac37bd/fcr:metadata Service: 70297811697440
  Load LDP (4.1ms) http://localhost:8984/rest/dev/h7/02/q6/36/h702q636h/files/20579b2a-75ab-4fab-80cb-3bdaf6ac37bd Service: 70297811697440
  Rendering text template
  Rendered text template (0.0ms)
Sent data paper_template_j098zb10q_F1000ResearchTemplate.docx (4.5ms)
Completed 200 OK in 2477ms (Views: 4.3ms | ActiveRecord: 48.6ms)


[2018-03-05 02:34:07] ERROR NoMethodError: undefined method `split' for 18031:Integer
        /home/data2paper/.rvm/gems/ruby-2.4.2/gems/rack-2.0.3/lib/rack/handler/webrick.rb:98:in `block in service'
        /home/data2paper/.rvm/gems/ruby-2.4.2/gems/rack-2.0.3/lib/rack/handler/webrick.rb:90:in `each'
        /home/data2paper/.rvm/gems/ruby-2.4.2/gems/rack-2.0.3/lib/rack/handler/webrick.rb:90:in `service'
        /home/data2paper/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
        /home/data2paper/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
        /home/data2paper/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'

```

**Comment by anusharanganathan** [comment]
See PR #52 
This particular issue related to the content length in the header being an integer rather than string
